name: Sync Docs to Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Prepare wiki content
        run: |
          set -e
          # Map README -> Home.md
          cp README.md wiki/Home.md
          # Copy docs/*.md -> wiki
          for f in docs/*.md; do
            base=$(basename "$f")
            cp "$f" "wiki/$base"
          done
          # Optional: add index list to Home.md footer
          echo -e "\n---\n## Documentation Pages" >> wiki/Home.md
          for f in $(ls docs/*.md | sort); do
            base=$(basename "$f")
            title=${base%.md}
            if [ "$title" != "Home" ]; then
              echo "- [[${title//-/ }|$title]]" >> wiki/Home.md
            fi
          done
      - name: Commit & push wiki
        run: |
          cd wiki
          git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No wiki changes"
          else
            git commit -m "docs: sync from main repo"
            git push
          fi
