name: Sync Docs to Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'docs/**/*.md'

permissions:
  contents: write

jobs:
  sync:
    if: ${{ github.event.repository.has_wiki }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Prepare wiki content
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          cp README.md wiki/Home.md
          for f in docs/*.md; do
            base="$(basename "$f")"
            if [[ "${base,,}" == "home.md" ]]; then
              continue
            fi
            cp "$f" "wiki/$base"
          done
          docs_list=(docs/*.md)
          if (( ${#docs_list[@]} > 0 )); then
            {
              echo
              echo '---'
              echo '## Documentation Pages'
              for f in "${docs_list[@]}"; do
                base="$(basename "$f")"
                title="${base%.md}"
                pretty="${title//[-_]/ }"
                if [[ "${title,,}" == "home" ]]; then
                  continue
                fi
                echo "- [[${pretty}|${title}]]"
              done
            } >> wiki/Home.md
          fi
      - name: Commit & push wiki
        run: |
          set -e
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No wiki changes"
            exit 0
          fi
          git commit -m "docs: sync from main repo (${GITHUB_SHA::7})"
          for i in 1 2 3; do
            if git push; then
              echo "Wiki updated."
              exit 0
            fi
            echo "Push failed (attempt $i), retrying in 5s..."
            sleep 5
          done
          echo "Push failed after retries" >&2
          exit 1
